// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIh1Iu1M7QAo-lfYHbRjEFY---nBvPGO8',
    appId: '1:56969920442:web:63ceaf484fe3f4e8f1a783',
    messagingSenderId: '56969920442',
    projectId: 'auth-firebsae-flutter',
    authDomain: 'auth-firebsae-flutter.firebaseapp.com',
    storageBucket: 'auth-firebsae-flutter.appspot.com',
    measurementId: 'G-P9RK5SJ6EF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMbzYUVBXtjXvMQkb1SRf-d0Vi4VZos0k',
    appId: '1:56969920442:android:20fc58c019b3d95af1a783',
    messagingSenderId: '56969920442',
    projectId: 'auth-firebsae-flutter',
    storageBucket: 'auth-firebsae-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBykBWAaWMSoqsNI9y1nebtiP8OQnmwCEo',
    appId: '1:56969920442:ios:64f94ed83f1672c8f1a783',
    messagingSenderId: '56969920442',
    projectId: 'auth-firebsae-flutter',
    storageBucket: 'auth-firebsae-flutter.appspot.com',
    iosClientId: '56969920442-csv00adllibusbefndt92kulfvpspo3k.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthAuthenticationFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBykBWAaWMSoqsNI9y1nebtiP8OQnmwCEo',
    appId: '1:56969920442:ios:529b4a082a1e0becf1a783',
    messagingSenderId: '56969920442',
    projectId: 'auth-firebsae-flutter',
    storageBucket: 'auth-firebsae-flutter.appspot.com',
    iosClientId: '56969920442-uueg03junjn6kharjdk21e6unggfrgde.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthAuthenticationFlutter.RunnerTests',
  );
}
